// Baralhos do jogo, organizados em "decks" selecionáveis antes de iniciar a partida.
//
// - "casual": baralho autoral, humor genérico/absurdo, seguro pra qualquer grupo.
// - "cancelavel": baralho oficial de Cards Against Humanity (edição em português),
//   incluído aqui sob a licença Creative Commons BY-NC-SA 2.0
//   (https://creativecommons.org/licenses/by-nc-sa/2.0/) — ver "Terms of Use" do
//   material original. Uso permitido desde que: (1) dado crédito a Cards Against
//   Humanity LLC, (2) não seja usado comercialmente, (3) qualquer distribuição ou
//   modificação mantenha a mesma licença. Cartas "Pick 2" do material original
//   foram omitidas porque o motor do jogo (v1) só suporta uma lacuna por rodada.

/** Cartas pretas: use "_____" para indicar a lacuna. */
const CASUAL_BLACK = [
  "Depois de anos de silêncio, finalmente descobri o segredo da felicidade: _____.",
  "O que o síndico do prédio não pode saber: _____.",
  "Antes de dormir, sempre penso em _____.",
  "A nova matéria obrigatória nas escolas será _____.",
  "Meu terapeuta disse que preciso conversar sobre _____.",
  "O motivo real do apocalipse zumbi foi _____.",
  "Não existe presente de aniversário melhor do que _____.",
  "A embalagem agora traz um aviso: contém _____.",
  "Pergunta da entrevista de emprego: como você lida com _____?",
  "O plano B, caso tudo dê errado, é _____.",
  "A receita secreta da vovó levava, além de amor, _____.",
  "O que estragou o casamento foi _____ ter aparecido no bolo.",
  "Cientistas descobriram que _____ pode curar a ressaca.",
  "A última coisa que ouvi antes de desmaiar foi _____.",
  "___ + café da manhã = perfeição.",
  "O verdadeiro motivo de eu estar atrasado hoje: _____.",
  "Isso vai direto pro meu currículo: _____.",
  "A nova atração do parque se chama '_____'.",
  "Ninguém fala sobre isso, mas todo mundo pensa em _____ no trânsito.",
  "O manual de instruções dizia para nunca combinar isso com _____.",
];

/** Cartas brancas: frases/expressões curtas. */
const CASUAL_WHITE = [
  "Um espanador existencial",
  "Aquele tio que só fala de bitcoin",
  "Uma dança da chuva mal coordenada",
  "17 abas abertas sobre o mesmo assunto",
  "Um pombo com Wi-Fi",
  "Chorar discretamente no autosserviço do mercado",
  "Um podcast sobre podcasts",
  "A vergonha alheia em forma de gente",
  "Meias furadas com estampa de coração",
  "Um grupo de WhatsApp da família às 6h da manhã",
  "Fingir que entendeu o gráfico na reunião",
  "Um robô aspirador com trauma",
  "Aquele silêncio depois de uma piada ruim",
  "Comer pipoca no cinema errado",
  "Um influenciador de produtividade improdutivo",
  "A ansiedade pré-post no LinkedIn",
  "Um estagiário com poder demais",
  "Ficar de pé no ônibus vazio por educação",
  "Um cactus com síndrome do pânico",
  "Aquele 'vamos marcar' que nunca vira nada",
  "Um karaokê involuntário no chuveiro",
  "Trocar de faixa no trânsito sem seta",
  "Um horóscopo genérico o suficiente pra qualquer um",
  "A boa e velha crise existencial de terça-feira",
  "Um professor universitário sem microfone e sem noção de volume",
  "O último pedaço de pizza que ninguém assume",
  "Um chefe que 'só quer alinhar rapidinho'",
  "Dançar sozinho na cozinha às 2h",
  "Um gato julgando suas decisões de vida",
  "A internet caindo bem na hora H",
  "Um powerpoint com 40 slides de introdução",
  "Aquele carinha do delivery que sabe seu pedido de cor",
  "Um bug que vira feature",
  "Uma playlist só de músicas tristes às 3 da manhã",
  "O sensor de pia automática que nunca funciona",
  "Um elevador com espelho e ninguém olhando pra ninguém",
  "A frase 'isso não vai doer nada'",
  "Um debate acalorado sobre qual pia é a certa no rodízio",
  "Aquele momento de dúvida: dar tchau de novo ou já foi?",
  "Um vizinho que faz reforma às 7h de domingo",
  "O terror de ouvir 'a gente precisa conversar'",
];

/**
 * Baralho oficial de Cards Against Humanity (edição PT-BR), cartas "Pick 1".
 * © Cards Against Humanity LLC — usado sob CC BY-NC-SA 2.0. Conteúdo adulto,
 * ofensivo e non-PC por design; ver aviso de conteúdo na tela de lobby.
 */
const CANCELAVEL_BLACK = [
  "O que é mais emo?",
  "Atirei o pau no gato / Mas o gato não morreu / Dona Chica admirou-se / Do _____ que o gato deu.",
  "Papai, por que mamãe está chorando?",
  "Durante sua infância, Salvador Dalí fez centenas de pinturas de _____.",
  "Como eu perdi minha virgindade?",
  "Em 1.000 anos, quando o dinheiro de papel for uma memória distante, como nós iremos pagar por bens e serviços?",
  "O Museu de História Natural acabou de lançar uma exibição interativa sobre _____.",
  "A Infraero agora proíbe _____ em aviões.",
  "É lamentável que os jovens hoje em dia estão todos se envolvendo com _____.",
  "A CBF baniu _____ do futebol por dar aos jogadores uma vantagem injusta.",
  "Qual é o prazer secreto do Batman?",
  "O próximo livro de J.K. Rowling: Harry Potter e a Câmara de _____.",
  "Me desculpe, Professor, mas eu não consegui fazer meu dever de casa por causa da _____.",
  "O que eu trouxe do Paraguai?",
  "_____. É impossível comer um só!",
  "Qual é minha anti-droga?",
  "Enquanto os Estados Unidos disputavam com a União Soviética para ver quem chegava primeiro à Lua, o governo do México destinava milhões de pesos em pesquisas sobre _____.",
  "No novo Filme Original do Disney Channel, Hannah Montana luta com _____ pela primeira vez.",
  "Qual meu poder secreto?",
  "Qual a dieta do momento?",
  "O que Vin Diesel comeu no jantar?",
  "Quando o Faraó se mostrou irredutível, Moisés invocou uma praga de _____.",
  "Como eu estou afirmando meu status de relacionamento?",
  "Dizem que na prisão do Carandiru se podia trocar 200 cigarros por _____.",
  "Depois do terremoto, Sean Penn trouxe _____ para o povo do Haiti.",
  "Ao invés de carvão nos dias de hoje Papai Noel dá às crianças malcriadas _____.",
  "A vida dos índios Tapajós foi mudada totalmente quando o homem branco os apresentou a _____.",
  "O que o governo está fazendo para as crianças da favela obterem sucesso?",
  "Talvez ela tenha nascido com isso. Talvez seja _____.",
  "Nos momentos finais de Michael Jackson, ele pensou _____.",
  "Pessoas brancas gostam de _____.",
  "Por que estou todo dolorido?",
  "Um jantar romântico a luz de velas não está completo sem _____.",
  "O que eu preciso trazer do passado para convencer as pessoas que sou um poderoso mago?",
  "LIGUE AGORA PARA 011-1406 E ADQUIRA JÁ O SEU _____.",
  "A viagem de estudo da classe foi completamente arruinada por causa _____.",
  "Qual é o melhor amigo da mulher?",
  "Querida Márcia, eu estou tendo problemas com _____ e gostaria de seu conselho.",
  "Quando eu for Presidente do Brasil, eu vou criar o Ministério de _____.",
  "O que meus pais estão escondendo de mim?",
  "O que nunca falha para se tentar animar uma festa?",
  "O que se melhora com a idade?",
  "_____: Bom até a última gota.",
  "Eu tenho 99 problemas mas _____ não é um deles.",
  "_____. Pegadinha do Malandro!",
  "O novo reality show da MTV tem oito celebridades decadentes vivendo com _____.",
  "O que vovó acharia pertubador, porém ao mesmo tempo elegante?",
  "Durante o sexo, eu gosto de pensar sobre _____.",
  "O que fez meu último relacionamento terminar?",
  "Que som é esse?",
  "_____. E é assim que quero morrer.",
  "Porque eu estou grudento?",
  "Qual é o próximo McLanche Feliz?",
  "O que tem de tonelada no Paraíso?",
  "Eu ainda não sei com quais armas a III Guerra Mundial será lutada, mas a IV Guerra Mundial será lutada com _____.",
  "O que sempre faz com que você consiga transar?",
  "_____: testado pelas crianças, aprovado pelas mães.",
  "Porque eu não consigo dormir a noite?",
  "Que cheiro é esse?",
  "O que ajuda Obama a relaxar?",
  "Assim expira o mundo / Assim expira o mundo / Não com uma explosão, mas com _____.",
  "Chegando a Broadway está temporada: _____: O Musical.",
  "Mas antes de matá-lo Sr. Bond, Eu devo lhe mostrar _____.",
  "Estudos mostram que ratos de laboratório navegam através de labirintos 50% mais rápido, após serem expostos a _____.",
  "Daqui a pouco na ESPN 2: O Campeonato Mundial de _____.",
  "Quando eu for bilionário, eu irei erguer uma estátua de 20 metros para comemorar _____.",
  "Guerra! Pra que serve?",
  "O que me causa gases incontroláveis?",
  "Que cheiro tem as pessoas velhas?",
  "O que eu estou abandonando pela quaresma?",
  "A medicina alternativa está reconhecendo os poderes curativos de _____.",
  "Os E.U.A. começaram a enviar _____ de pára-quedas para as crianças do Afeganistão.",
  "O que é que José Sarney prefere?",
  "O que você não espera encontrar em sua comida chinesa?",
  "Eu bebo para esquecer _____.",
  "_____. Toca aqui, irmão.",
];

/**
 * Baralho oficial de Cards Against Humanity (edição PT-BR), cartas brancas.
 * © Cards Against Humanity LLC — usado sob CC BY-NC-SA 2.0.
 */
const CANCELAVEL_WHITE = [
  "Uma maldição cigana.",
  "Um momento de silêncio.",
  "Uma festa onde só tem macho.",
  "Um policial honesto sem nada a perder.",
  "A Fome.",
  "Uma bactéria comedora de carne.",
  "Cobras voadoras taradas.",
  "Cagar para o Terceiro Mundo.",
  "Mandar mensagens sexuais por SMS.",
  "Metamorfos.",
  "Estrelas Pornôs.",
  "Estuprar e pilhar.",
  "72 virgens.",
  "Um tiroteio.",
  "Um paradoxo de viagem no tempo.",
  "Uma autêntica comida Mexicana.",
  "Bijuterias.",
  "Consultores.",
  "Dívidas astronômicas.",
  "Problemas com o papai.",
  "O Selo de Aprovação de Donald Trump™.",
  "Derrubar o candelabro sobre seus inimigos e subir pela corda.",
  "O Ex-Presidente George W. Bush.",
  "Nu frontal Completo.",
  "Injeções Hormonais.",
  "Botar um ovo.",
  "Ficar pelado e assistir a Nickelodeon.",
  "Fingir se importar.",
  "Cair no ridículo.",
  "Compartilhar agulhas.",
  "Meleca de nariz.",
  "A inevitável destruição do universo.",
  "O milagre do nascimento.",
  "O arrebatamento.",
  "Mandando ver.",
  "Classe Média Sofre.",
  "Deveres conjugais.",
  "Roberval, o ladrão de chocolate.",
  "Desodorante para corpo AXE.",
  "O Sangue de Cristo.",
  "Um terrível acidente com depilação a laser.",
  "BATMAN!!!",
  "Agricultura.",
  "Um retardado fortão.",
  "Seleção Natural.",
  "Abortos clandestinos.",
  "Comer todos os biscoitos antes da feira beneficente.",
  "Os braços da Michelle Obama.",
  "O World of Warcraft.",
  "Furar olho.",
  "Obesidade.",
  "Vídeos homoeróticos de jogadores de Vôlei.",
  "Tétano.",
  "Uma exibição sexual.",
  "Torção testicular.",
  "Rodízio de carnes por R$ 9,90.",
  "Pizza de chocolate.",
  "Kanye West.",
  "Queijo Quente.",
  "Ataque de Velociraptors.",
  "Tirar a camisa.",
  "Esmegma.",
  "Alcoolismo.",
  "Um homem de meia idade de patins.",
  "Um abraço dos Ursinhos Carinhosos.",
  "Beber, Cair e Levantar.",
  "Um Pirulitão.",
  "Auto-piedade.",
  "Crianças com coleiras.",
  "Preliminares meia-boca.",
  "A Bíblia Sagrada.",
  "Pornô Alemão Sado-Masô.",
  "Pegar fogo.",
  "Gravidez adolescente.",
  "Gandhi.",
  "Deixar uma mensagem de voz bizarra.",
  "Ganchos.",
  "Representantes do SAC.",
  "Uma ereção que dura mais de 4 horas.",
  "Meus genitais.",
  "Pegar mulher na clínica de abortos.",
  "Ciência.",
  "Não reciprocar no sexo oral.",
  "Passarinho que não voa.",
  "Uma boa cheirada.",
  "Afogamento simulado.",
  "Um café da manhã balanceado.",
  "Escolas públicas.",
  "Literalmente tirar doce de crianças.",
  "O Criança Esperança.",
  "Uma passada de mão clandestina.",
  "Notas de Post-It passivo-agressivas.",
  "A equipe de Ginástica Olímpica da China.",
  "Mude para a Porto Seguro®.",
  "Urinar um pouquinho.",
  "Vídeo caseiro da Ana Maria Braga chorando embaixo da mesa.",
  "Polução Noturna.",
  "Os judeus.",
  "Minha bunda.",
  "Coxas poderosas.",
  "Paquerar com idosos.",
  "Pato Purific, confie no bico do pato!",
  "Uma suave passada de mão na coxa.",
  "Tensão sexual.",
  "O fruto proibido.",
  "Esqueleto do He-Man.",
  "Comida para gatos Whiskas®.",
  "Ser rico.",
  "Doce, doce vingança.",
  "Tucanos.",
  "Um jumento com flatulência.",
  "Natalie Portman.",
  "Dar uma pegadinha.",
  "Pilotos Kamikazes.",
  "Sean Connery.",
  "A Agenda Gay.",
  "O Retirante Nordestino.",
  "Um falcão de caça.",
  "Coroinhas.",
  "Jarbas do Tang.",
  "Ficar com tanta raiva que lhe dá uma ereção.",
  "Amostras grátis.",
  "Um grande fuzuê a troco de nada.",
  "Fazer a coisa certa.",
  "A Lei do Ventre Livre.",
  "Lactação.",
  "Paz mundial.",
  "RoboCop.",
  "Malandragem.",
  "Justin Bieber.",
  "Oompa-Loompas.",
  "Um forró inapropriado.",
  "Puberdade.",
  "Fantasmas.",
  "Uma cirurgia de implante de silicone nos seios que ficou assimétrica.",
  "Mãos de seresteiro.",
  "Dar uma dedada.",
  "Boris Casoy prendendo o saco na porta do chuveiro.",
  "Danoninho®.",
  "Brutalidade Policial.",
  "Joaquim Silvério dos Reis.",
  "Pré-adolescentes.",
  "Tirar o escalpo.",
  "Segurar um risinho ao ouvir menção do Peru.",
  "\"Tuitar\".",
  "Darth Vader.",
  "Uma punheta meia-boca.",
  "Exatamente o que você esperava.",
  "Esperar um arroto e acabar vomitando.",
  "Ritalina™.",
  "Células-Tronco.",
  "Decote de bom-gosto.",
  "Sexo de Pandas.",
  "Uma lobotomia com um picador de gelo.",
  "Tom Cruise.",
  "Herpes Labial.",
  "Esperma de Baleia.",
  "Mendigos sem-teto.",
  "A mão-naquilo, aquilo-na-mão.",
  "Incesto.",
  "O Pac-Man gozando incontrolavelmente.",
  "Um mímico tendo um ataque do coração.",
  "Ted Boy Marino.",
  "Deus.",
  "Lavar bem as dobrinhas.",
  "\"Chuva dourada\".",
  "Emoções.",
  "Lamber a comida pra marcar como sua.",
  "Nova Schin.",
  "A Placenta.",
  "Combustão Humana Espontânea.",
  "Amizade Colorida.",
  "Pintura com os dedos.",
  "Cheiro de gente velha.",
  "Morrer de disenteria.",
  "Meus demônios internos.",
  "Uma arma de água cheia de xixi de gato.",
  "Hermes da Fonseca.",
  "Dormir de conchinha.",
  "A erva.",
  "Briga de Galo.",
  "Fogo amigo.",
  "Fernando Henrique Cardoso.",
  "Uma festa de aniversário fracassada.",
  "Uma mulata safada.",
  "Olimpíadas de matemática.",
  "Um pônei.",
  "Francisco Cuoco.",
  "Cavalgando em direção ao Pôr do Sol.",
  "Um M. Night Shyamalan plot twist.",
  "Cabelo pixaim.",
  "Destruição mútua assegurada.",
  "Pedófilos.",
  "Levedura.",
  "Roubo de Túmulos.",
  "Comer o último bisão conhecido.",
  "Catapultas.",
  "Gente Pobre.",
  "Liberdade, ainda que tardia.",
  "O Xaxado.",
  "A Força.",
  "Chicoteando a bunda dela.",
  "Design Inteligente.",
  "Bucho-furado.",
  "AIDS.",
  "Fotos de Seios.",
  "O Super Homem de Nietzche.",
  "Sarah Palin.",
  "American Gladiators.",
  "Ficar realmente chapado.",
  "Cientologia.",
  "Inveja do penis.",
  "Rezar até deixar de ser gay.",
  "Se curtir.",
  "Dois anões cagando em um balde.",
  "A KKK.",
  "Genghis Khan.",
  "Metanfetaminas.",
  "Servidão.",
  "Não falar com estranhos.",
  "A Bop It™.",
  "A carreira de ator de Shaquille O'Neal.",
  "Empinar.",
  "Justiça de um Vigilante.",
  "Compensação.",
  "Bukkake pixelado.",
  "Uma vida completa de tristeza.",
  "Racismo.",
  "Arremesso de Anão.",
  "Brilho do Sol e Arco-Iris.",
  "Um macaco fumando charuto.",
  "Enchente de verão.",
  "O Testículo perdido de Lance Armstrong.",
  "Tirar um sarro.",
  "Os terroristas.",
  "Britney Spears aos 55 anos.",
  "Atitude.",
  "Começar a cantar e dançar do nada.",
  "Lepra.",
  "Gloryholes.",
  "Estar com os faróis acesos.",
  "O coração de uma criança.",
  "Filhotes!",
  "Acordar seminu no estacionamento do Bob's.",
  "Dental Dams.",
  "A vagina da Raquel de Queiroz.",
  "O períneo; o meinho; a periferia do parque de diversões.",
  "Ouvir atentamente.",
  "Limpeza étnica.",
  "Os escravos de Jó jogando caxangá.",
  "A mão invisível.",
  "Esperando até o casamento.",
  "Estupidez inconcebível.",
  "Euphoria™ por Calvin Klein.",
  "Repassar o presente.",
  "Auto canibalismo.",
  "Disfunção erétil.",
  "Minha coleção de brinquedinhos eróticos.",
  "O Papa.",
  "Pessoas Brancas.",
  "Tentáculo Hentai.",
  "Boris Casoy vomitando compulsivamente enquanto aranhas eclodem de seu cérebro e saem por seus canais lacrimais.",
  "Muito gel de cabelo.",
  "Seppuku.",
  "Dupla do mesmo sexo de patinação no gelo.",
  "Trapaceando nas Paraolimpiadas.",
  "Carisma.",
  "Keanu Reeves.",
  "Sean Penn.",
  "Nickelback.",
  "Uma espiadinha.",
  "Cagando e andando. Pra sempre.",
  "Menstruação.",
  "Crianças com cancer no reto.",
  "Uma surpresa salgadinha.",
  "O Sul.",
  "A violação dos nossos mais básicos direitos.",
  "YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
  "Estupro em encontro.",
  "Ser fabuloso.",
  "Necrofilia.",
  "Centauros.",
  "Beakman do Mundo de Beakman.",
  "Pessoas Negras.",
  "Cavalaria.",
  "Biscoito Passatempo™.",
  "Putas.",
  "Os muito deficientes.",
  "Órfãos adoráveis.",
  "MechaHitler.",
  "Cagadas de fogo.",
  "Outro maldito filme de vampiro.",
  "Mola Maluca enrolada.",
  "O verdadeiro significado do Natal.",
  "Estrogênio.",
  "Um burrito picante de café-da-manhã.",
  "Aquela parada que eletrocuta seu abdomen.",
  "Expelir pedra nos rins.",
  "Clareamento anal.",
  "Michael Jackson.",
  "Melhorias cibernéticas.",
  "Caras que não ligam.",
  "Cobertores com varíola.",
  "Masturbação.",
  "Insinuações classistas.",
  "Peido de buceta.",
  "Esconder uma ereção.",
  "Calcinhas comestíveis.",
  "Viagra®.",
  "Sopa que está muito quente.",
  "O Profeta Maomé (que Alá o abençoe).",
  "Sexo surpresa!",
  "Promoção da semana do Subway.",
  "Beber sozinho.",
  "Mão furada.",
  "Múltiplos ferimentos de faca.",
  "Se cagar todo.",
  "Abuso infantil.",
  "Contas anais.",
  "Casualidade civil.",
  "Tirar de dentro.",
  "Robert Downey, Jr.",
  "Comida de cavalo.",
  "Um chapéu realmente maneiro.",
  "Kim Jong-il.",
  "Um penteado rebelde.",
  "Fraternidades judias.",
  "Uma minoria minúscula.",
  "Meter na bunda.",
  "Dar comida a Cláudia Jimenez.",
  "Ensinar um robô a amar.",
  "Uma lata de chute-no-traseiro.",
  "Um moinho cheio de corpos.",
  "Conde Chocula.",
  "Usar a cueca no lado B.",
  "Raio da Morte.",
  "Telhado de vidro.",
  "Um isopor cheio de órgãos humanos.",
  "O sonho americano.",
  "Barris de cerveja.",
  "Peido molhado.",
  "Volta atrás.",
  "Bebês mortos.",
  "Prepúcio.",
  "Solos de saxofone.",
  "Italianos.",
  "Um feto.",
  "Atirar pra cima com um rifle enquanto cercado por porcos selvagens.",
  "José Sarney.",
  "Amputados.",
  "Eugenia.",
  "Meu status de relacionamento.",
  "Christopher Walken.",
  "Abelhas?",
  "Harry Potter erótica.",
  "Ensino Médio.",
  "Ficar Bêbado com Cepacol.",
  "Nazistas.",
  "10 gramas de heroína mexicana.",
  "Stephen Hawking falando palavrão.",
  "Pais mortos.",
  "Permanência do objeto.",
  "Polegares Opositores.",
  "Questões do vestibular racistas.",
  "Bla-bla-bla.",
  "Motosserras para mãos.",
  "Nicolas Cage.",
  "Concurso de Beleza Infantil.",
  "Explosões.",
  "Cheirar cola.",
  "Boris Casoy sendo perseguido por uma revoada de urubus.",
  "Repressão.",
  "Boa noite cinderela.",
  "Minha vagina.",
  "Calça de cavalgada.",
  "Um assassinato cruel.",
  "Dando 110%.",
  "Sua Alteza Real, Rainha Elizabeth II.",
  "A Trilha de Lágrimas.",
  "Ser marginalizado.",
  "Goblins.",
  "Esperança.",
  "O Rev. Dr. Martin Luther King, Jr.",
  "Um micropenis.",
  "Minha alma.",
  "A maior confusão.",
  "Vikings.",
  "Pessoas Gostosas.",
  "Sedução.",
  "Um complexo de édipo.",
  "Gansos.",
  "Aquecimento Global.",
  "Música New Age.",
  "Hot Pockets®.",
  "Fazer bico.",
  "Atropelamento.",
  "Voto das mulheres.",
  "Uma camisinha defeituosa.",
  "Você Decide.",
  "Crianças africanas.",
  "O Massacre da Candelária.",
  "Barack Obama.",
  "Asiáticos que não são bom em matemática.",
  "Velhinhos Japoneses.",
  "Trocar gentilesas.",
  "Heteronormatividade.",
  "Abrir o Mar Vermelho.",
  "Arnold Schwarzenegger.",
  "Boquete no carro.",
  "Um abdômen espetacular.",
  "Pudim de Figo.",
  "Um leão de zoológico deprimido.",
  "Um saco de feijões mágicos.",
  "Escolhas erradas.",
  "Minha vida sexual.",
  "Auschwitz.",
  "Uma tartaruga mordendo a cabeça do seu pênis.",
  "Uma detonação termonuclear.",
  "O clitóris.",
  "O Big Bang.",
  "Minas terrestres.",
  "Amigos que comem todos os aperitivos.",
  "Bodes comendo latas.",
  "A Dança da Fadinha Doce.",
  "Se masturbar em uma poça de lágrimas de crianças.",
  "Carne humana.",
  "Um tempo particular.",
  "O Quilombo dos Palmares.",
  "Piadas sobre o Holocausto na hora errada.",
  "Um mar de problemas.",
  "Fantasias de madeireiro.",
  "A voz do Morgan Freeman.",
  "Mulheres em comerciais de iogurte.",
  "Estimulante masculino natural.",
  "Ser um puta dum feiticeiro.",
  "Piercing genital.",
  "Travestis que enganam.",
  "Lutas de travesseiro sexys.",
  "Ovos.",
  "Vovó.",
  "Fricção.",
  "Estraga-prazeres.",
  "Peidando e andando.",
  "Ser um imbecil com crianças.",
  "Colocar armadilhas na casa para protegê-las de ladrões.",
  "Travesseiros Suecos.",
  "Morrer.",
  "O furacão Katrina.",
  "Os gays.",
  "A tolice dos homens.",
  "Homens.",
  "Os Amish.",
  "Ovos de Pterodáctilo.",
  "Dinâmicas de grupo.",
  "Um tumor no cérebro.",
  "Cartas Contra a Humanidade.",
  "O próprio medo.",
  "Lady Gaga.",
  "O leiteiro.",
  "Uma boca suja.",
];

const DECKS = {
  casual: {
    id: "casual",
    name: "Modo Casual",
    description: "Humor absurdo e genérico — seguro pra qualquer grupo.",
    mature: false,
    black: CASUAL_BLACK,
    white: CASUAL_WHITE,
  },
  cancelavel: {
    id: "cancelavel",
    name: "Modo Cancelável",
    description:
      "Baralho oficial de Cards Against Humanity (PT-BR) — humor pesado, ofensivo e non-PC. Recomendado só pra maiores de 18 e estômago forte.",
    mature: true,
    black: CANCELAVEL_BLACK,
    white: CANCELAVEL_WHITE,
  },
};

const DECK_LIST = Object.values(DECKS).map(({ id, name, description, mature }) => ({
  id,
  name,
  description,
  mature,
}));

module.exports = { DECKS, DECK_LIST };
